---
- name: Wait until the lock file is removed
  wait_for:
    path: /var/lib/dpkg/lock-frontend
    state: absent
    timeout: 300

- name: install unzip
  become: yes
  become_method: sudo
  apt:
    name: unzip
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
    install_recommends: false
  tags:
    - unzip
